Schoology.App.MyValor/Controllers/DirectoryController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Net;
using System.Web.UI.WebControls;
using Schoology.App.MyValor.Models;
using RestSharp;
using RestSharp.Authenticators;
using NLog;
using LoggingLibrary;
using NLog.Targets;
using NLog.Config;
using API_Library_2._0;

namespace Schoology.App.MyValor.Controllers
{
    public class DirectoryController : Controller
    {
        //CM - NLog from logging library
        public static GenerateLogger logGenerator = new GenerateLogger("Active Directory", "https://master-api1.nextworld.net/v2/LoggingConfiguraiton", "jake.vossen@nextworld.net", "gmAHF7eS9!BI$20MzFkk0nW3qz&LdXykwUs!RSBq");
        public static Logger logger = logGenerator.getLogger();

        //CM - using api lib
        //public static SchoologyMyValor apiGen = new SchoologyMyValor();
        public static SchoolDirectory apiGen = new SchoolDirectory();

        private static List<API_Library_2._0.GetParentStudentDirectory_Result> _totalUserList { get; set; }

        private List<API_Library_2._0.GetParentStudentDirectory_Result> LoadStudents(string searchString, List<string> gradefilter)
        {

            // Create the list to hold the users.
            List<API_Library_2._0.GetParentStudentDirectory_Result> filterUserList = new List<API_Library_2._0.GetParentStudentDirectory_Result>();

            // Initialize the Grid.MVC searching, sorting and search string.
            GridMVCModel gridMVCModel = new GridMVCModel();

            ViewBag.gridPage = 1;
            ViewBag.gridFilter = "";
            ViewBag.gridColumn = "";
            ViewBag.gridDir = 0;
            ViewBag.SearchString = "";

            // Proformance Issues
            // We only want to load data when we hit this page.
            // If the post-back for grid paging and filtering, do not reload the data.

            // If no query strings, load the data once and store in static variable
            if (Request.QueryString.Count == 0)
            {

                // Get the Parent's emails using the students EA7RecordsId
                //List<GetParentStudentDirectory_Result> parentsEmailList = db.GetParentStudentDirectory().ToList();
                //_totalUserList = db.GetParentStudentDirectory().ToList(); //Kurt 
                _totalUserList = GetParentsAndStudents(); //Rick Inmann

                // Get the users from Schoology Json File instead of calling the Schoology API directly.
                //_totalUserList = UserService.Instance.GetUsersJsonFile();

                // Set the Grid.MVC grid-page to 1 because if we go to the details page and return it will reload all the data.
                ViewBag.gridPage = 1;

            }
            else
            {
                // Set the view bag variables to be passed to the details page so we can return back to where we started from.
                // Grid Page
                if (!string.IsNullOrWhiteSpace(Request.QueryString["grid-page"]))
                {
                    ViewBag.gridPage = int.Parse(Request.QueryString["grid-page"]);
                }

                // Grid Filter
                if (!string.IsNullOrWhiteSpace(Request.QueryString["grid-filter"]))
                {
                    ViewBag.gridFilter = Request.QueryString["grid-filter"];
                }

                // Grid Sort Direction
                if (!string.IsNullOrWhiteSpace(Request.QueryString["grid-dir"]))
                {
                    ViewBag.gridDir = Request.QueryString["grid-dir"];
                }

                // Grid Sort Column
                if (!string.IsNullOrWhiteSpace(Request.QueryString["grid-column"]))
                {
                    ViewBag.gridColumn = Request.QueryString["grid-column"];
                }

                // Filter Textbox
                if (!string.IsNullOrWhiteSpace(Request.QueryString["SearchString"]))
                {
                    ViewBag.SearchString = Request.QueryString["SearchString"];
                }

            }

            //List<GetParentStudentDirectory_Result> tmplist = new List<GetParentStudentDirectory_Result>();

            //    }

            // Filter the list by FirstName or LastName.
            if (!string.IsNullOrEmpty(searchString))
            {
                ViewBag.SearchString = searchString;
                
                // Now that we have all the users, check to see if we need to filter them.
                if (!string.IsNullOrEmpty(searchString))
                {

                    if (IsNumeric(searchString))
                    {
                        filterUserList = _totalUserList.Where(s => s.CityStatePostBlock1.Contains(searchString) || s.CityStatePostBlock2.Contains(searchString)).ToList();
                    }
                    else
                    {
                        filterUserList = _totalUserList.Where(s => s.LastName.ToLower().Contains(searchString.ToLower())
                                                                   || s.FirstName.ToLower().Contains(searchString.ToLower())
                                                                   || s.GradeLevel.ToLower().Contains(searchString.ToLower())).ToList();
                    }
                }
            }
            else
            {
                filterUserList = _totalUserList;
            }

            if (gradefilter.Contains("9th") || gradefilter.Contains("10th") || gradefilter.Contains("11th") || gradefilter.Contains("12th"))
            {
                if (gradefilter.Contains("9th") && gradefilter.Count() == 1)
                {
                    filterUserList = filterUserList.Where(t => t.GradeLevel.ToLower() == "9th grade").ToList(); 
                }
                if (gradefilter.Contains("9th") && gradefilter.Contains("10th") && gradefilter.Count() == 2)
                {
                    filterUserList = filterUserList.Where(t => t.GradeLevel.ToLower() == "9th grade" || t.GradeLevel.ToLower() == "10th grade").ToList();
                }
                if (gradefilter.Contains("9th") && gradefilter.Contains("11th") && gradefilter.Count() == 2)
                {
                    filterUserList = filterUserList.Where(t => t.GradeLevel.ToLower() == "9th grade" || t.GradeLevel.ToLower() == "11th grade").ToList();
                }
                if (gradefilter.Contains("9th") && gradefilter.Contains("12th") && gradefilter.Count() == 2)
                {
                    filterUserList = filterUserList.Where(t => t.GradeLevel.ToLower() == "9th grade" || t.GradeLevel.ToLower() == "12th grade").ToList();
                }
                if (gradefilter.Contains("9th") && gradefilter.Contains("10th") && gradefilter.Contains("11th") && gradefilter.Count() == 3)
                {
                    filterUserList = filterUserList.Where(t => t.GradeLevel.ToLower() == "9th grade" || t.GradeLevel.ToLower() == "10th grade" || t.GradeLevel.ToLower() == "11th grade").ToList();
                }
                if (gradefilter.Contains("10th") && gradefilter.Count() == 1)
                {
                    filterUserList = filterUserList.Where(t => t.GradeLevel.ToLower() == "10th grade").ToList();
                }
                if (gradefilter.Contains("10th") && gradefilter.Contains("11th") && gradefilter.Count() == 2)
                {
                    filterUserList = filterUserList.Where(t => t.GradeLevel.ToLower() == "10th grade" || t.GradeLevel.ToLower() == "11th grade").ToList();
                }
                if (gradefilter.Contains("10th") && gradefilter.Contains("12th") && gradefilter.Count() == 2)
                {
                    filterUserList = filterUserList.Where(t => t.GradeLevel.ToLower() == "10th grade" || t.GradeLevel.ToLower() == "12th grade").ToList();
                }
                if (gradefilter.Contains("10th") && gradefilter.Contains("11th") && gradefilter.Contains("12th") && gradefilter.Count() == 3)
                {
                    filterUserList = filterUserList.Where(t => t.GradeLevel.ToLower() == "10th grade" || t.GradeLevel.ToLower() == "11th grade" || t.GradeLevel.ToLower() == "12th grade").ToList();
                }
                if (gradefilter.Contains("11th") && gradefilter.Count() == 1)
                {
                    filterUserList = filterUserList.Where(t => t.GradeLevel.ToLower() == "11th grade").ToList();
                }
                if (gradefilter.Contains("11th") && gradefilter.Contains("12th") && gradefilter.Count() == 2)
                {
                    filterUserList = filterUserList.Where(t => t.GradeLevel.ToLower() == "11th grade" || t.GradeLevel.ToLower() == "12th grade").ToList();
                }
                if (gradefilter.Contains("12th") && gradefilter.Count() == 1)
                {
                    filterUserList = filterUserList.Where(t => t.GradeLevel.ToLower() == "12th grade").ToList();
                }
                //filterUserList = filterUserList.Where(t => t.GradeLevel.Any(s => gradefilter.ToString().Contains(s))).ToList();
            }

            gridMVCModel.GridPage = Convert.ToInt32(ViewBag.gridPage);
            gridMVCModel.GridFilter = ViewBag.gridFilter;
            gridMVCModel.GridColumn = ViewBag.gridColumn;
            gridMVCModel.GridDir = Convert.ToInt32(ViewBag.gridDir);
            gridMVCModel.SearchString = ViewBag.searchString;

            Session["gridMVCModel"] = gridMVCModel;

            //List<Attendance> list = attendanceRoot.attendance.Where(x => x.date == "2015-06-03").ToList();

            return filterUserList;
        }

       /* public static List<API_Library_2._0.GetParentStudentDirectory_Result> GetParentsAndStudents()
        {

Schoology.App.MyValor/Views/Directory/Details.cshtml
@model API_Library_2._0.GetParentStudentDirectory_Result

<script src="~/Scripts/jquery.blockUI.js" type="text/javascript"></script>
<link rel="Stylesheet" href="~/Content/themes/redmond/jquery-ui.css" />

@{
    ViewBag.Title = "Student & Parent Directory Details";
}

<h3>@ViewBag.Title</h3>
<style>
    .detail { font-size: 16px; margin-left: 10px; }
</style>


<p>
    @Html.ActionLink("Back to List", "Index",
        new RouteValueDictionary {
                                    { "grid-page", @ViewBag.gridPage },
                                    { "grid-filter", @ViewBag.gridFilter },
                                    { "grid-column", @ViewBag.gridColumn },
                                    { "grid-dir", @ViewBag.gridDir },
                                    { "SearchString", @ViewBag.SearchString }
                                 })
</p>

<div style="margin: 3em 5em;">
    <div style="display: inline-block;">
        <div style="font-weight: bold; font-size: 16px; float: left;">@Html.DisplayFor(model => model.LastName), @Html.DisplayFor(model => model.FirstName)</div>&nbsp;&nbsp;&nbsp;
            <div style="display: inline-block;">(@Html.DisplayFor(model => model.GradeLevel))</div>
    </div><br /><br />
    <div class="detail">email: @Html.DisplayFor(model => model.StudentEmail)</div>
    @{
        if (Model.Siblings != "")
        {
            <div class="detail">siblings: @Html.DisplayFor(model => model.Siblings)</div>
        }
    }
    <br/>
    <div class="detail">@Html.DisplayFor(model => model.Parents1)</div>
    <div class="detail">@Html.DisplayFor(model => model.AddressBlock1)</div>
    <div class="detail">@Html.DisplayFor(model => model.CityStatePostBlock1)</div>
    <div class="detail">@Html.DisplayFor(model => model.HomePhone1)</div>
    @{
        if (Model.Parents2 != "")
        {
            <br/>
            <div class="detail">@Html.DisplayFor(model => model.Parents2)</div>
            <div class="detail">@Html.DisplayFor(model => model.AddressBlock2)</div>
            <div class="detail">@Html.DisplayFor(model => model.CityStatePostBlock2)</div>
            <div class="detail">@Html.DisplayFor(model => model.HomePhone2)</div>
        }
    }


</div>
<div class="row">

    <div class="col-md-5">

        <dl class="dl-horizontal">

            <dt>
                Last Name:
            </dt>

            <dd>
                @Html.DisplayFor(model => model.LastName)
            </dd>

            <dt>
                First Name:
            </dt>

            <dd>
                @Html.DisplayFor(model => model.FirstName)
            </dd>

            <dt>
                Email:
            </dt>

            <dd>
                @Html.DisplayFor(model => model.StudentEmail)
            </dd>

            <dt>
                Grade Level:
            </dt>

            <dd>
                @Html.DisplayFor(model => model.GradeLevel)
            </dd>

            <dt>
                Siblings:
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Siblings)
            </dd>
        </dl>
    </div>
</div>




<div class="row">

    <div class="col-md-5">

        <dl class="dl-horizontal">

            <dt>
                Parents:
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Parents1)
            </dd>

            <dt>
                Address:
            </dt>

            <dd>
                @Html.DisplayFor(model => model.AddressBlock1)
            </dd>

            <dt>
                
            </dt>

            <dd>
                @Html.DisplayFor(model => model.CityStatePostBlock1)
            </dd>

            <dt>
                Phone:
            </dt>

            <dd>
                @Html.DisplayFor(model => model.HomePhone1)
            </dd>



        </dl>
    </div>
</div>


@{ if (@Model.Parents2 != "")
                         {
<div class="row">

    <div class="col-md-5">

        <dl class="dl-horizontal">

            <dt>
                Parents:
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Parents2)
            </dd>

            <dt>
                Address:
            </dt>

            <dd>
                @Html.DisplayFor(model => model.AddressBlock2)
            </dd>

            <dt>

            </dt>

            <dd>
                @Html.DisplayFor(model => model.CityStatePostBlock2)
            </dd>

            <dt>
                Phone:
            </dt>

            <dd>
                @Html.DisplayFor(model => model.HomePhone2)
            </dd>



        </dl>
    </div>
</div>
}
}

<p>
    @Html.ActionLink("Back to List", "Index",
        new RouteValueDictionary {
                                    { "grid-page", @ViewBag.gridPage },
                                    { "grid-filter", @ViewBag.gridFilter },
                                    { "grid-column", @ViewBag.gridColumn },
                                    { "grid-dir", @ViewBag.gridDir },
                                    { "SearchString", @ViewBag.SearchString }
                                 })
</p>

Schoology.App.MyValor/Views/Directory/Index.cshtml
@model IEnumerable<API_Library_2._0.GetParentStudentDirectory_Result>
@using GridMvc.Html
@using GridMvc.Sorting

@{
    ViewBag.Title = "Student & Parent Directory";
}

<h3>@ViewBag.Title</h3>

@using (Html.BeginForm("Index", "Directory", FormMethod.Get))
{
    <div>
        @Html.TextBox("SearchString", ViewBag.SearchString as string, new { style = "width: 300px;", placeholder = "search for name, zip code or grade here"})
        &nbsp;&nbsp;&nbsp;<input id="Search" type="submit" value="Search" />
        <input id="Clear" type="submit" value="Clear" />
    </div>
    <div style="position: absolute; top: 65px; right: 10em; border: solid 1px; width: 320px; padding:5px 20px;">Grades: &nbsp;&nbsp;9th&nbsp;&nbsp;@Html.CheckBox("chbox9")&nbsp;&nbsp;10th&nbsp;&nbsp;@Html.CheckBox("chbox10")&nbsp;&nbsp;11th&nbsp;&nbsp;@Html.CheckBox("chbox11")&nbsp;&nbsp;12th&nbsp;&nbsp;@Html.CheckBox("chbox12")</div>
    <div style="position: absolute; top: 145px; right: 1em; width: 380px; color:#bcbcbc;">Click on a row to reveal a students parent information.</div>
}
<style>  
    #hiddenrow { column-count: 4; }
    .grid-table tr:hover { background-color: white !important; border: 2px solid gray; }
	.parent-info tr:hover { border: none; }
	.grid-table tr:nth-child(even) {border: none !important; }
    a:link {
        text-decoration: none;
        }

    a:visited {
            text-decoration: none;
        }
    </style>
<script>

    $(function () {

        // Clear the search grid
        $("#Clear").on("click", function (event) {
            $("#SearchString").val("");
        });

        // Grid row select event code
        //pageGrids.studentGrid.onRowSelect(function (e) {
        //    alert(e.row.uid);
        //});

    });
@*    //@Html.Grid(Model).Columns(column => { }).Attributes(id => "id-of-your-choice") *@
</script>
<div id="row" onclick="showDiv(this.id)"> </div>
    @Html.Grid(Model).Named("studentGrid").Columns(columns =>
    {
        /* Adding "OrderID" column: */
        columns.Add(model => model.LastName)
               .Titled("Last Name")
               .Filterable(true)
               .Sortable(true)
               .SortInitialDirection(GridSortDirection.Ascending)
               .SetWidth(150);

        columns.Add(model => model.FirstName)
               .Titled("First Name")
               .Filterable(true)
               .Sortable(true)
               .SetWidth(100);

        columns.Add(model => model.GradeLevel)
               .Titled("Grade Level")
               .Filterable(true)
               .Sortable(true)
               .SetWidth(100);

        columns.Add(model => model.StudentEmail)
               .Titled("Email")
               .Filterable(false)
               .Sortable(false)
               .SetWidth(150);
        columns.Add()
               .Encoded(false)
               .Sanitized(false)
               .SetWidth(250)
               .RenderValueAs(d =>

                     @<b>
                          <a href="#"><span style="color: #808080;">&nbsp;&nbsp;&nbsp;&nbsp;&#9660</span></a>      <!-- &#10552; -->      </b>);

            columns.Add()
               .Encoded(false)
               .Sanitized(false)
               .SetWidth(500)
               .RenderValueAs(d =>
                   @<b>
                   </b>);

    }).WithPaging(10).Selectable(false)

<script>
    function showDiv(id) {
        //alert("id = " + id);
        var divid = "h" + id;
        //alert("divid = " + divid);
        var state = document.getElementById(divid).style.display;
        if (state === '') { document.getElementById(divid).style.display = "none"; }
        else { document.getElementById(divid).style.display = ""; }
    }
</script>